### ISSUE TITLE
popup after sms verification.

### ISSUE THREAD

**Issue by onurakdogan** [bruno222/twilio-flex-plugin-sso#23]
After login, a modal comes and asks for username and password.
ACCOUNT_SID AND
Although I entered the AUTH_TOKEN values ​​correctly, I cannot login.

Error: 

{
"code": 70004,
"detail": "Your AccountSid or AuthToken was incorrect.",
"message": "authentication failed: Invalid issuer in the Assertion/Response. Was 'https://accounts.google.com/o/saml2?idpid=C00hiegpn', but expected 'https://serverless-sso-XXXX-dev.twil.io/sso/saml'",
"more_info": "https://www.twilio.com/docs/errors/70004",
"status": 401
}

**Comment by bruno222** [comment]
(solved via twilio suport ticket)
